// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_WA1o56yr8wygUlxu8J0Z0AdbFHFpZE',
    appId: '1:200727485886:web:cbad0bf52070b0b6ea2def',
    messagingSenderId: '200727485886',
    projectId: 'union-shop-ec1b0',
    authDomain: 'union-shop-ec1b0.firebaseapp.com',
    storageBucket: 'union-shop-ec1b0.firebasestorage.app',
    measurementId: 'G-KVQ5EBSXPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzCEjL4HCF61PdbpfYlZ_lSq-IdyGAwKU',
    appId: '1:200727485886:android:c75075856b8d8a16ea2def',
    messagingSenderId: '200727485886',
    projectId: 'union-shop-ec1b0',
    storageBucket: 'union-shop-ec1b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwLwqZ6jdePCtJSTjD0U8CFPku8QQr6Fc',
    appId: '1:200727485886:ios:910dee4f10584be1ea2def',
    messagingSenderId: '200727485886',
    projectId: 'union-shop-ec1b0',
    storageBucket: 'union-shop-ec1b0.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwLwqZ6jdePCtJSTjD0U8CFPku8QQr6Fc',
    appId: '1:200727485886:ios:910dee4f10584be1ea2def',
    messagingSenderId: '200727485886',
    projectId: 'union-shop-ec1b0',
    storageBucket: 'union-shop-ec1b0.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_WA1o56yr8wygUlxu8J0Z0AdbFHFpZE',
    appId: '1:200727485886:web:924cfa8e4662bbe4ea2def',
    messagingSenderId: '200727485886',
    projectId: 'union-shop-ec1b0',
    authDomain: 'union-shop-ec1b0.firebaseapp.com',
    storageBucket: 'union-shop-ec1b0.firebasestorage.app',
    measurementId: 'G-JQLF85R032',
  );
}
