// Mocks generated by Mockito 5.4.6 from annotations
// in union_shop/test/helpers/mock_annotations.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i11;

import 'package:firebase_auth/firebase_auth.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:union_shop/models/cart.dart' as _i2;
import 'package:union_shop/models/collection.dart' as _i8;
import 'package:union_shop/models/product.dart' as _i5;
import 'package:union_shop/repositories/cart_repository.dart' as _i3;
import 'package:union_shop/repositories/collection_repository.dart' as _i7;
import 'package:union_shop/repositories/product_repository.dart' as _i6;
import 'package:union_shop/services/auth_service.dart' as _i9;
import 'package:union_shop/view_models/cart_view_model.dart' as _i12;
import 'package:union_shop/view_models/product_view_model.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCart_0 extends _i1.SmartFake implements _i2.Cart {
  _FakeCart_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i3.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Cart> getCart() => (super.noSuchMethod(
        Invocation.method(
          #getCart,
          [],
        ),
        returnValue: _i4.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #getCart,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Cart>);

  @override
  _i4.Future<void> addItem(
    _i5.Product? product,
    int? quantity, {
    Map<String, String>? selectedOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [
            product,
            quantity,
          ],
          {#selectedOptions: selectedOptions},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeItem(String? cartItemId) => (super.noSuchMethod(
        Invocation.method(
          #removeItem,
          [cartItemId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateQuantity(
    String? cartItemId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            cartItemId,
            quantity,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCart() => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i6.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Product>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Product>>.value(<_i5.Product>[]),
      ) as _i4.Future<List<_i5.Product>>);

  @override
  _i4.Future<_i5.Product?> fetchById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchById,
          [id],
        ),
        returnValue: _i4.Future<_i5.Product?>.value(),
      ) as _i4.Future<_i5.Product?>);

  @override
  _i4.Future<List<_i5.Product>> search(String? query) => (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.Product>>.value(<_i5.Product>[]),
      ) as _i4.Future<List<_i5.Product>>);
}

/// A class which mocks [CollectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCollectionRepository extends _i1.Mock
    implements _i7.CollectionRepository {
  MockCollectionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.Collection>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Collection>>.value(<_i8.Collection>[]),
      ) as _i4.Future<List<_i8.Collection>>);

  @override
  _i4.Future<_i8.Collection?> fetchById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchById,
          [id],
        ),
        returnValue: _i4.Future<_i8.Collection?>.value(),
      ) as _i4.Future<_i8.Collection?>);

  @override
  _i4.Future<List<_i8.Collection>> fetchFeatured() => (super.noSuchMethod(
        Invocation.method(
          #fetchFeatured,
          [],
        ),
        returnValue: _i4.Future<List<_i8.Collection>>.value(<_i8.Collection>[]),
      ) as _i4.Future<List<_i8.Collection>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i10.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i10.User?>.empty(),
      ) as _i4.Stream<_i10.User?>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i10.User?> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i10.User?>.value(),
      ) as _i4.Future<_i10.User?>);

  @override
  _i4.Future<_i10.User?> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i10.User?>.value(),
      ) as _i4.Future<_i10.User?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CartViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartViewModel extends _i1.Mock implements _i12.CartViewModel {
  MockCartViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Cart get cart => (super.noSuchMethod(
        Invocation.getter(#cart),
        returnValue: _FakeCart_0(
          this,
          Invocation.getter(#cart),
        ),
      ) as _i2.Cart);

  @override
  int get totalItems => (super.noSuchMethod(
        Invocation.getter(#totalItems),
        returnValue: 0,
      ) as int);

  @override
  double get totalPrice => (super.noSuchMethod(
        Invocation.getter(#totalPrice),
        returnValue: 0.0,
      ) as double);

  @override
  String get formattedTotal => (super.noSuchMethod(
        Invocation.getter(#formattedTotal),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#formattedTotal),
        ),
      ) as String);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> updateRepository(_i3.CartRepository? newRepository) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRepository,
          [newRepository],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addToCart(
    _i5.Product? product,
    int? quantity, {
    Map<String, String>? selectedOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [
            product,
            quantity,
          ],
          {#selectedOptions: selectedOptions},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromCart(String? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeFromCart,
          [itemId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateQuantity(
    String? itemId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [
            itemId,
            quantity,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCart() => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshCart() => (super.noSuchMethod(
        Invocation.method(
          #refreshCart,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> runWithLoading(_i4.Future<void> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithLoading,
          [operation],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProductViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductViewModel extends _i1.Mock implements _i14.ProductViewModel {
  MockProductViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> loadProductById(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #loadProductById,
          [productId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshProduct() => (super.noSuchMethod(
        Invocation.method(
          #refreshProduct,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> runWithLoading(_i4.Future<void> Function()? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithLoading,
          [operation],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
